version: '3.8'

services:

  gateway:
    build: gateway
    image: gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image: postgres:15.1-alpine
    container_name: postgres_db_container
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit